### PR TITLE
Fix GCC 15 build errors from discarded-qualifiers

### PR DESCRIPTION
**Pull request by ghost**
I get the following errors when building with gcc 15:
```
../../../libsys/prsnam.c: In function ‘_decb_prsnam’:
../../../libsys/prsnam.c:47:13: error: assignment discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
   47 |         dot = strchr(filename, '.');
      |             ^
../../../cocofuse/cocofuse.c: In function ‘coco_rename’:
../../../cocofuse/cocofuse.c:346:12: error: assignment discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
  346 |         p1 = strrchr(path, '/');
      |            ^
../../../cocofuse/cocofuse.c:347:12: error: assignment discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
  347 |         p2 = strrchr(newname, '/');
      |            ^
```
Please review the changes I made and let me know if they are appropriate. I tested the build on Arch Linux with gcc 15.2.1.

### CODE REVIEW

**Comment by tlindner** [comment]
In cocofuse.c could you omit the use of strdup() and just change the declaration like you did in prsnam.c?

**Comment by ghost** [comment]
I couldn't change `*p1` and `*p2` to const because they get modified. Then I tried this:
```
-static int coco_rename(const char *path, const char *newname)
+static int coco_rename(char *path, char *newname)
```
And got this error:
```
../../../cocofuse/cocofuse.c:687:19: error: initialization of ‘int (*)(const char *, const char *)’ from incompatible pointer type ‘int (*)(char *, char *)’ [-Wincompatible-pointer-types]
  687 |         .rename = coco_rename,
      |                   ^~~~~~~~~~~
```
I couldn't figure out a way around that. It looks like fuse is expecting function signatures to have `const char*` or something. 

Are you trying to avoid `strdup()` or the extra complexity of the change in general? I can re-write it using `malloc()` and `strcpy()` instead if you are trying to avoid `strdup()`. 
Or do the changes cause the function to no longer operate correctly? I admit I'm coming at this from a "get it to build" point of view. Maybe the fix is to change the CFLAGS to not treat this as an error?

**Comment by ghost** [comment]
Upon further study, I revised to a much simpler fix that will maintain the current behavior. I squashed and corrected earlier changes. Please review these changes and let me know how it looks. Thank you.

**Comment by tlindner** [comment]
I have a faint memory of `strdup()` being a problem in the past. But I've compiled on the platforms I have available  and the CI here successfully compiled on Windows, so I guess we're ok now.

**Comment by ghost** [comment]
I don't know if you noticed I changed the branch, as per my last comment, which is what you merged. It is a much simpler fix and should maintain existing behaviour, but I want to make sure you reviewed it. I appologize if this was not the correct way to go about this. Here is the diff of my latest change to the original main:
```
diff --git a/cocofuse/cocofuse.c b/cocofuse/cocofuse.c
index 5fb238e..642e196 100644
--- a/cocofuse/cocofuse.c
+++ b/cocofuse/cocofuse.c
@@ -343,8 +343,8 @@ static int coco_rename(const char *path, const char *newname)
         *    - If so just rename.
         *    - If not, rename then delete orginal.
         */
-       p1 = strrchr(path, '/');
-       p2 = strrchr(newname, '/');
+       p1 = strrchr((char *)path, '/');
+       p2 = strrchr((char *)newname, '/');

        if (p1 == NULL || p2 == NULL)
        {
diff --git a/libsys/prsnam.c b/libsys/prsnam.c
index cc49740..baabf91 100644
--- a/libsys/prsnam.c
+++ b/libsys/prsnam.c
@@ -41,10 +41,9 @@ error_code _os9_prsnam(const char *filename)
 error_code _decb_prsnam(const char *filename)
 {
        error_code ec = 0;
-       char *dot;

        /* 1. Check if filename contains a dot */
-       dot = strchr(filename, '.');
+       const char *dot = strchr(filename, '.');

:
```

**Comment by tlindner** [comment]
I did, in fact, not notice you changed patch before I hit the merge button. But I did notice it soon after. It looked good, so we're cool. All my fault, I should have noticed.
